version: '3'
services:
  stock-keeper:
    image: stock-keeper
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    environment:
      POSTGRESQL_URI: postgres://stockperson:coolpw@postgres/stockkeeper
  postgres:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: stockperson
      POSTGRES_PASSWORD: coolpw
      POSTGRES_DB: stockkeeper
      # POSTGRES_PORT: 5432
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql